version: '2'

services:
  dotnet:
    build:
      context: ./app/src/api
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    volumes:
    - /home/florian/Documents/ProjetMatos/app/src/api:/home
    networks:
    - sdnet
  mysql:
    image: mysql
    ports:
    - 3306:3306
    volumes:
    - /home/florian/Documents/ProjetMatos/app/dist/data:/home
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=ProjetMatos
    networks: 
    - sdnet
networks:
  sdnet:
    driver: "bridge"