version: '2'

services:
  dotnet:
    build:
      context: ./app/src/api
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    volumes:
    - /mnt/hgfs/ProjetMatos/app/src/api:/home
    networks:
    - sdnet
networks:
  sdnet:
    driver: "bridge"